"""Add download attribute to Recording

Revision ID: 3faa5ba323bc
Revises: 5404830dcbb4
Create Date: 2019-11-15 16:01:11.138904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3faa5ba323bc'
down_revision = '5404830dcbb4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording',
        sa.Column('downloads', sa.Integer(), nullable=False,
            server_default=sa.sql.expression.text("0")
        )
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recording', 'downloads')
    # ### end Alembic commands ###
